# Generated by Django 3.1 on 2020-08-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('admission_year', models.CharField(max_length=50)),
                ('class_number', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
    ]
